[preface]
:sectnums!:

= はじめに

== この本について

この本では、Go言語の標準パッケージのうち `go/` で始まるものと、準標準パッケージとして `golang.org/x/tools/go` から始まるものについて紹介します。ドキュメントとソースコードの中間となることを目指し、実例を交えつつ、ドキュメントだけからはただちに知ることのできないAPI同士の関連や、全体としての使い方に焦点を当てて解説します。

== なぜ「GoのためのGo」なのか

Go言語はシンプルさを念頭にデザインされた言語です。仕様は単純さ、明瞭さのために小さく収められていますが、そのため表現力に欠けているとか、コードが冗長になるという印象を持つ人も多いでしょう。

しかし一般に言っても、ソフトウェアエンジニアリングのプロセスは、読み書きされるプログラムだけに依るものではありません。視点を拡げ、Go言語を取りまくツール群を含めて見てみると、間違いと思われるコードを検出する link:https://pkg.go.dev/cmd/go#hdr-Report_likely_mistakes_in_packages[`go vet`] や既存のコードを新しいものに書き換える link:https://go.dev/blog/gofix[`go fix`] などが標準で提供されていること、またコードの静的解析を行うためのパッケージ(link:https://pkg.go.dev/golang.org/x/tools/go/analysis[`golang.org/x/tools/go/analysis`]) が存在し、さまざまなツールと連携できるようになっていることからも、Goはその周辺ツールを含めたエコシステムも含めてプログラミングの体験を設計していると言えるでしょう。

Goが標準で提供する `go/*` および `golang.org/x/tools/go/*` パッケージ群は、Goのプログラムを対象とし、解析や操作を行うためのAPIを提供します。これらのAPIを利用し、一種のメタプログラミングを行うことで、Go言語をよりよく使っていくことができるはずです。つまり、GoのためのGoです。

== 対象バージョン

この本の内容は、Goバージョン{go_version}に基いています。が、ほとんどの内容は改訂前で、バージョン1.6に基いている可能性があります。

:sectnums:
