= コメントとドキュメント

これまではプログラムの実行に関わるコード本体をプログラムから扱う方法について見てきました。この章ではGoソースコード中のコメントを扱っていきます。

コメントはドキュメントの記述にも使用されており、そのためのAPIも `go/doc` パッケージとして用意されています。

== コメントの解析

`parser.ParseFile` の第4引数 `mode` に `parser.ParseComments` 定数を指定することで、構文解析の結果にコメントを含めることができます。

godoc::go/parser.ParseFile[]

goexample::parsecomment[]
goexample::parsecomment[output]

こうやって解析されたコメントは通常の構文木とは別に、`ast.File` 構造体の `Comments` フィールドに格納されます。`Comments` フィールドは `[]*ast.CommentGroup` として宣言されています。`ast.CommentGroup` は連続して続くコメントをひとまとめにしたもので、

* `/* ... \*/` 形式のコメントなら `/*` から `*/` まで
* `// ...` 形式なら `//` から行末まで

が、ひとつの `ast.Comment` に対応します。

godoc::go/ast.CommentGroup[]
godoc::go/ast.Comment[]

例えばコメントが以下のように書かれていた場合、それぞれ `CommentGroup` は2つ生成され、それぞれ2個の `Comment` を持ちます。

[source,go]
----
// foo
/* bar */

// baz
// quux
----

コメントも `ast.Node` インタフェースを実装し、位置情報を保持しています。ソースコードの文字列化の際は、この位置情報にもとづいてコメントが正しく挿入されるようになっています。

== Goにおけるドキュメント

Goではトップレベルの型や関数のすぐ直前のコメントがそのAPIのドキュメントである、と標準的に定められています（link:https://go.dev/blog/godoc[Godoc: documenting Go code]）。標準の `go doc` コマンドもこのルールに則ってドキュメントを表示します。

.go doc go/parser.ParseFile
....
% go doc go/parser.ParseFile
func ParseFile(fset *token.FileSet, filename string, src interface{}, mode Mode) (f *ast.File, err error)
    ParseFile parses the source code of a single Go source file and returns the
    corresponding ast.File node. The source code may be provided via the
    filename of the source file, or via the src parameter.
...
....

[source,go]
.src/go/parser/interface.go
----
// ParseFile parses the source code of a single Go source file and returns
// the corresponding ast.File node. The source code may be provided via
// the filename of the source file, or via the src parameter.
// ...
//
func ParseFile(fset *token.FileSet, filename string, src interface{}, mode Mode) (f *ast.File, err error) {
----

== doc.Package

Goパッケージの（ソースコードから生成される）ドキュメントは、`doc.Package` として表現されます。

godoc::go/doc.Package[]

`doc.Package` は `doc.New` 関数によって `ast.Package`（<<パッケージ>>）から生成されます。

godoc::go/doc.New[]

NOTE: ドキュメントに "`New takes ownership of the AST pkg and may edit or overwrite it.`" とある通り、`doc.New` は与えられた `pkg` を書き換えることがあります。

`mode` パラメータの指定によって、非公開のAPIに関してもドキュメントを収集することができます。

godoc::go/doc.AllDecls[]

ifdef::wip[]
=== doc.Packageのレイアウト

WARNING: WIP

`doc.Package` 構造体はドキュメントの表示に都合のよいように、整理された状態で

== 例示のためのテスト

WARNING: WIP

* doc.Examples
endif::wip[]
