= 型解析

ここまで見てきたようなGoの抽象構文木を扱うAPIを知っていれば、Goプログラムを対象にしてできることの7割ほどは実現できたも同然です。しかし、

* ソースコード中に登場する名前が定義された位置や、
* ある型がインタフェースを実装しているか

など、プログラムの構造を越えたより高度な情報が必要になった場合は、**型解析**に手を出す必要があります。

この章では、Goパッケージの型チェックと型にまつわるデータ構造を提供する `go/types` パッケージのAPIを見ていきます。

[WARNING]
====
TODO

- 名前解決
- 定数畳み込み
- 型推論
- その他構文的なチェック
====

== 型チェックを行う

`types` パッケージによる型チェックは、`types.Config` 構造体の `Check` メソッドを呼ぶところから始まります。

godoc::go/types.Config.Check[]

`files []ast.File` には、ひとつのパッケージを構成する構文解析されたファイル群を指定します。<<ファイルの構文解析>> で `files` の要素を生成した際に使用した `fset` も引数として渡します。

最後の引数である `info *types.Info` は、パッケージ内の型にまつわる詳細な情報を格納する先として指定します。単純に型チェックを行いたいだけの場合は `nil` でも構いません。

goexample::typechecksimple[]

goexample::typechecksimple[output]

パッケージのトップレベルに定義された `s` という変数の型が `string` であるという情報が得られました。

このように、型チェックおよび型情報の取得は `Config` 構造体をエントリポイントとしてパッケージごとに行います。結果は <<types.Package>> 構造体と、ここでは登場しませんでしたが <<types.Info>> 構造体に格納されます。

== パッケージのインポート

先ほどの例では `Config.Importer` を設定していました。これは `types.Importer` という型を持つフィールドです。

godoc::go/types.Importer[]

`types.Importer` は、パッケージのパスを解決し、そのパッケージに関する型レベルの情報を返すインタフェースです。具体的には、コンパイルされたパッケージオブジェクトを `GOPATH` から探し出し、解析するのが仕事です。

この具体的な実装を提供するのが `go/importer` パッケージです。`importer.Default()` は実行中のバイナリのコンパイラ（`runtime.Compiler`）に対応するインポートの実装を返します。

godoc::go/importer.Default[]

以下はパッケージを読み込み、そのパッケージが公開している名前および依存しているパッケージの情報を印字する例です。

goexample::importer[]

goexample::importer[output]

プログラムの型チェックにはインポートしているパッケージがどんな名前と型を提供するのか知る必要があるため、`Config` 構造体の `Importer` フィールドという形でその実装を指定します。

== types.Config

`types.Config` 構造体が `go/types` パッケージのエントリポイントとなります。

godoc::go/types.Config[]

各フィールドを調整することで、`Check()` による型チェックを行う際の挙動をカスタマイズできます。

特に、`Error func(err error)` は型チェックの際に生じたエラーを全て受け取るコールバックとして便利です。これが `nil` である場合、最初のエラーが起きた時点で型チェックが停止します。

== 型チェックのエラー

型チェック時のエラーは `types.Error` 構造体によって表現されます。

godoc::go/types.Error[]

エラーの起きた位置情報に加え、`Soft` フィールドを持っています。このフィールドは、当該のエラーが「ソフト」であるかどうかを示します。ソフトなエラーは、型チェックそのものには影響を与えません。具体的には、以下のエラーです。

* `import` されたパッケージが使用されていない
* 定義された変数が使用されていない
* ラベルが利用されていない・重複している
* `:=` の左辺に新しい変数が登場していない
* `init` 関数の本体が存在しない
// 関数の本体については https://go.dev/ref/spec#Function_declarations
* C形式の `for` 文の後処理文で変数を定義しようとしている +
  …… `for i := 0; i < 10; i, j := i+1, i {` のような形。構文解析の時点では受けつけてしまいます
// parseSimpleStmt。spec でも "PostStmt = SimpleStmt ." となってる

// TODO: 型チェックだけでなくこういう言語的なチェックも行われること初めの方で言及

////
% pt --nogroup -w softErrorf src/go/types
src/go/types/labels.go:38:			check.softErrorf(lbl.pos, "label %s declared but not used", lbl.name)
src/go/types/labels.go:136:					check.softErrorf(lbl.pos, "label %s already declared", name)
src/go/types/labels.go:151:							check.softErrorf(
src/go/types/errors.go:89:func (check *Checker) softErrorf(pos token.Pos, format string, args ...interface{}) {
src/go/types/resolver.go:356:							check.softErrorf(obj.pos, "missing function body")
src/go/types/resolver.go:456:						check.softErrorf(obj.pos, "%q imported but not used", path)
src/go/types/resolver.go:458:						check.softErrorf(obj.pos, "%q imported but not used as %s", path, obj.name)
src/go/types/resolver.go:468:			check.softErrorf(pos, "%q imported but not used", pkg.path)
src/go/types/assignments.go:329:		check.softErrorf(pos, "no new variables on left side of :=")
src/go/types/stmt.go:62:			check.softErrorf(v.pos, "%s declared but not used", v.name)
src/go/types/stmt.go:565:				check.softErrorf(lhs.Pos(), "no new variable on left side of :=")
src/go/types/stmt.go:644:				check.softErrorf(lhs.Pos(), "%s declared but not used", lhs.Name)
src/go/types/stmt.go:710:			check.softErrorf(s.Pos(), "cannot declare in post statement")
////

以下で、ソフトなエラーとそうでない重篤なエラーの例を確認できます。

goexample::typecheckerrors[]

goexample::typecheckerrors[output]

== パッケージの型情報

`types.Config.Check()` によって得られる型情報は、パッケージに対応する `types.Package` と、補助的で詳細な情報である `types.Info` で表現されます。

=== types.Package

godoc::go/types.Package[]

`types.Package` 構造体は公開されたフィールドを持たないため、メソッドからアクセスします。

あまり意味のない例ですが、以下では `$GOROOT/src/cmd/cover` ディレクトリのソースコードの型チェックを行っています。

goexample::typechecknameandpath[]

goexample::typechecknameandpath[output]

== typesにおけるスコープ

`Path` や `Name` などの基本的な情報の他に有用なのは、解析されたパッケージのスコープ情報でしょう。

godoc::go/types.Package.Scope[]

godoc::go/types.Scope[]

`types.Scope` 構造体は型におけるスコープを表します。スコープは基本的に、そこに所属する名前から、それが表すオブジェクト（-> <<オブジェクト>>）へのマッピングであると考えられます。

スコープは階層構造になっていて、`Parent()` および `Child()` メソッドによりその親（ひとつ外側のスコープ）や子にアクセスできます。

godoc::go/types.Scope.Parent[]

godoc::go/types.Scope.Child[]

// ast.Scope との対応はどんなもん

=== ユニバーススコープ

最も外側のスコープをユニバーススコープと呼ぶことは前に述べたとおりですが、`ast` パッケージと違い `types` パッケージにはこれが定義されています。

以下の例では、ユニバーススコープに定義されている名前を列挙しています。

goexample::typesuniverse[]

goexample::typesuniverse[output]

組み込みの関数や型がユニバーススコープに属していることが分かります。

== typesにおけるオブジェクト

`types` パッケージにおけるオブジェクトは、`ast` パッケージにおけるそれと異なり、インタフェースとして表現されています。また、より詳しい情報を持ちます。

godoc::go/types.Object[]

`ast.Object` における `Kind` フィールドに対応するものを持たないため、type switchでその種類を判別することになります。typesパッケージで表現されるオブジェクトの種類と、対応するデータ型は以下のようになっています。

* 組み込み関数（`*types.Builtin`）
* 定数（`*types.Const`）
* 関数（`*types.Func`）
* ラベル（`*types.Label`）
* `nil` （`*types.Nil`）
* インポートされたパッケージ（`*types.PkgName`）
* 宣言された型（`*types.TypeName`）
* 宣言された変数など（`*types.Var`）

これらについて、以下で見ていきます。

=== types.Builtin

組み込み関数を表します。組み込み関数は決まった型を持たないため、`Type()` はinvalidな型を返します。

goexample::typesbuiltin[]

goexample::typesbuiltin[output]

=== types.Const

定数を表します。`Val()` メソッドは、その定数値を表す `go/constant` パッケージの値を返します。

godoc::go/types.Const.Val[]

https://go.dev/ref/spec#Constant_expressions[定数式]は型チェック時に評価され、値としてオブジェクトに保持されます（TODO: 定数畳み込み）。

goexample::typesconst[]

goexample::typesconst[output]

=== types.Func

関数を表します。より詳細には、

- 宣言された関数
- 具象メソッド
- （インタフェースの）抽象メソッド

です。

以下で、それぞれの場合（トップレベルの関数 `F`、型 `*T` のメソッド `F`、インタフェース `I` のメソッド `F`）の出現を確認しています。

goexample::typesfunc[]

goexample::typesfunc[output]

<1> パッケージスコープ内の名前にアクセスします。`F` はトップレベルの関数に、`T` および `I` は型名に対応するオブジェクトとして取得します。
<2> 型 `T` に属する最初のメソッドとして、`T.F()` に対応するオブジェクトを取得します。
<3> 型 `I` が指すインタフェース `interface { F() }` の最初の（抽象）メソッドとして、`I.F()` に対応するオブジェクトを取得します。

インタフェースの抽象メソッドと、それ以外の具象メソッドに対応するオブジェクトへアクセスする方法は微妙に異なりますが、これはあとの節で詳しく触れます。

=== types.PkgName

`import` 宣言によってインポートされたパッケージの名前を表します。

`Imported()` メソッドで、インポートされたパッケージに関する情報を保持する <<types.Package,`types.Package` 構造体>>を得られます。これは `Config.Check` で得られるのと同様のものです。

以下の例では、`fmtPkg` という名前でインポートした `fmt` パッケージと、同パッケージのエクスポートする `Errorf` 関数に対応するオブジェクトを取得しています。

インポートしたパッケージの名前はパッケージスコープではなくファイルスコープに導入されるため、後の節で説明する<<types.Info,`Info` 構造体>>を使ってファイルスコープを取得しています。

goexample::typespkgname[]

goexample::typespkgname[output]

NOTE: ファイル先頭の `package` 節で指定された名前はスコープに導入されないので、自パッケージの名前が `PkgName` の形で登場することはありません。

=== types.TypeName

WARNING: TBD

=== types.Var

WARNING: TBD

== types.Info

さて、`types.Scope` のメソッドを使うことで、パッケージ中に登場した名前に関する情報をオブジェクトとして得ることは一応可能です。しかしこれだけでは、

* あるオブジェクトがどこで定義されたのか
* ある式にどんな型が与えられたのか

などについて（ただちには）知ることができません。そこで `Check` 関数の最後の引数に渡す構造体、`types.Info` の出番となります。

godoc::go/types.Info[]

`types.Info` は型チェック中に得られた、詳細な情報を保持する構造体です。

WARNING: WIP

== 型の情報

=== types.Type

[appendix]
== types.Objectの階層

----
include::listings/types-object-hierarchy.txt[]
----

[appendix]
== types.Typeの階層

----
include::listings/types-type-hierarchy.txt[]
----
