= 型解析

ここまで見てきたようなGoの抽象構文木を扱うAPIを知っていれば、Goプログラムの静的な操作はある程度できるようになったと言っていいでしょう。しかし、より深く、

* ソースコード中に登場する名前が定義された位置や、
* ある型がインタフェースを実装しているか

など、プログラムの構造を越えたより高度な情報が必要になった場合は、**型解析**に手を出す必要があります。

この章では、Goパッケージの型チェックと型にまつわるデータ構造を提供する `go/types` パッケージのAPIを見ていきます。

[WARNING]
====
TODO

- 名前解決
- 定数畳み込み
- 型推論
- その他構文的なチェック
====

== 型チェックを行う

`types` パッケージによる型チェックは、`types.Config` 構造体の `Check` メソッドを呼ぶところから始まります。

godoc::go/types.Config.Check[]

`files []ast.File` には、ひとつのパッケージを構成する構文解析されたファイル群を指定します。<<ファイルの構文解析>> で `files` の要素を生成した際に使用した `fset` も引数として渡します。

最後の引数である `info *types.Info` は、パッケージ内の型にまつわる詳細な情報を格納する先として指定します。単純に型チェックを行いたいだけの場合は `nil` でも構いません。

goexample::typechecksimple[]

goexample::typechecksimple[output]

パッケージのトップレベルに定義された `s` という変数の型が `string` であるという情報が得られました。

このように、型チェックおよび型情報の取得は `Config` 構造体をエントリポイントとしてパッケージごとに行います。結果は <<types.Package>> 構造体と、ここでは登場しませんでしたが <<types.Info>> 構造体に格納されます。

== types.Config

`types.Config` 構造体が `go/types` パッケージのエントリポイントとなります。

godoc::go/types.Config[]

各フィールドを調整することで、`Check()` による型チェックを行う際の挙動をカスタマイズできます。

特に、`Error func(err error)` は型チェックの際に生じたエラーを全て受け取るコールバックとして便利です。これが `nil` である場合、最初のエラーが起きた時点で型チェックが停止します。

== パッケージのインポート

`types.Config.Importer` は、`types.Importer` という型を持つフィールドです。プログラムの型チェックを行うためにはインポートしているパッケージがどんな名前と型を提供するのか知る必要があるため、`Config` 構造体の `Importer` フィールドという形でその実装を指定します。

godoc::go/types.Importer[]

`types.Importer` は、パッケージのパスを解決し、そのパッケージに関する型レベルの情報を返すインタフェースです。

=== go/importer

この具体的な実装を提供していたが `go/importer` パッケージ**でした**。

でした、というのは、このパッケージはlink:++https://pkg.go.dev/cmd/go#hdr-Modules__module_versions__and_more++[Go modules]のリリース前につくられたもので、現在の標準的なモジュール管理方法であるGo modulesに対応していないためです。

このモジュールは非推奨とはなっていないものの、上記の理由により、外部のモジュールに依存するようなプログラムに対しては使うべきではないとされています。

インポートの解決に限らず、型解析には `golang.org/x/tools/go/packages` パッケージの利用が推奨されますが、ここで少々 `go/importer` について触れておきます。

==== importer.Default

`importer.Default()` は実行中のバイナリのコンパイラに対応するインポートの簡易な実装を返します。先述の通りGo modulesに対応しておらず、モジュールを `GOPATH` から読み込もうとするため、利用する機会はほとんどないでしょう。

godoc::go/importer.Default[]

以下は `log` パッケージを読み込み、そのパッケージが公開している名前および依存しているパッケージの情報を印字する例です。

goexample::importer[]
goexample::importer[output]

==== importer.ForCompiler

どちらにしろ利用が推奨されないパッケージではありますが、`token.FileSet` を渡すことができ、位置情報を正確に扱えるこちらのほうが `Default` よりよいとされています。

godoc::go/importer.ForCompiler[]

第2引数の `compiler` は使用するコンパイラを指定します。通常は `runtime.Compiler` つまり `"gc"` を指定します。

NOTE: Go 1.27時点では、`runtime.Compiler` の値は `"gc"` か `"gccgo"` のいずれかになりますが、実用的には `"gc"` のみだと考えて問題ないでしょう。

第3引数の `lookup` は、パッケージのパスを受け取り、そのパッケージのコンパイル済みファイルを返す関数です。

godoc::go/importer.Lookup[]

このファイルに含まれるエクスポートデータ（<https://go.dev/src/cmd/compile/README#7a-export>）はコンパイラによって生成され、パッケージがエクスポートする宣言の型情報などが含まれています。

具体的には、`go list -export <pkg>` で取得できるファイルになります。
このことを使って、自前でモジュールシステムに対応した `Importer` を実装できます。

goexample::importergolist[]
goexample::importergolist[output]

標準ではないパッケージの情報を読み取り、型情報を導けています。

== 型チェックのエラー

型チェック時のエラーは `types.Error` 構造体によって表現されます。

godoc::go/types.Error[]

エラーの起きた位置情報に加え、`Soft` フィールドを持っています。このフィールドは、当該のエラーが「ソフト」であるかどうかを示します。ソフトなエラーは、型チェックそのものには影響を与えません。具体的には、以下のエラーです。

* `import` されたパッケージが使用されていない
* 定義された変数が使用されていない
* ラベルが利用されていない・重複している
* `goto` がジャンプ先までの間の変数宣言を飛び越えている
* `:=` の左辺に新しい変数が登場していない
* `init` 関数の本体が存在しない
* 型パラメータを持つ関数の本体が存在しない
// 関数の本体については https://go.dev/ref/spec#Function_declarations
* `init` 関数や `main` パッケージの `main` 関数が型パラメータ・引数・戻り値を持っている
* C形式の `for` 文の後処理文で変数を定義しようとしている +
  …… `for i := 0; i < 10; i, j := i+1, i {` のような形。構文解析の時点では受けつけてしまいます
// parseSimpleStmt。spec でも "PostStmt = SimpleStmt ." となってる
* `range` で反復できない値に `range` を使っている、または反復変数の数が多すぎる
* 最後のパラメータ以外で可変長引数の `...` を使っている
* 型引数が型パラメータの制約を満たしていない
* 型制約でしか使えないインタフェース（`comparable` や型の集合を含むもの）を通常の型として使っている
* 型制約の和が重複している（`~int | ~int` など）
* 型パラメータの値を組み込み関数 `real`・`imag`・`complex` に渡している
// go.dev/issue/50937

// TODO: 型チェックだけでなくこういう言語的なチェックも行われること初めの方で言及

////
% go version
go version go1.27.1 darwin/arm64
% grep -rn "softErrorf(\|err.soft = true" go/types/*.go | grep -v _test | grep -v "func (check"
go/types/assignments.go:599:		check.softErrorf(pos, NoNewVar, "no new variables on left side of :=")
go/types/builtins.go:1118:		check.softErrorf(x, code, "%s not supported as argument to built-in %s for go1.18 (see go.dev/issue/50937)", x, predeclaredFuncs[id].name)
go/types/errors.go:249:	err.soft = true
go/types/call.go:163:			check.softErrorf(atPos(pos), InvalidTypeArg, "%s", err)
go/types/decl.go:783:		check.softErrorf(fdecl.Name, BadDecl, "generic function is missing function body")
go/types/labels.go:44:			check.softErrorf(lbl, UnusedLabel, "label %s declared and not used", lbl.name)
go/types/labels.go:136:					err.soft = true
go/types/labels.go:153:							check.softErrorf(
go/types/range.go:73:			check.softErrorf(&x, InvalidRangeExpr, "cannot range over %s: %s", &x, cause)
go/types/range.go:75:			check.softErrorf(&x, InvalidRangeExpr, "cannot range over %s", &x)
go/types/range.go:77:			check.softErrorf(sKey, InvalidIterVar, "range over %s permits no iteration variables", &x)
go/types/range.go:79:			check.softErrorf(sValue, InvalidIterVar, "range over %s permits only one iteration variable", &x)
go/types/range.go:81:			check.softErrorf(sExtra, InvalidIterVar, "range clause permits at most two iteration variables")
go/types/range.go:176:					check.softErrorf(lhs, InvalidRangeExpr, "cannot use iteration variable of type %s", x.typ())
go/types/signature.go:415:				check.softErrorf(t, InvalidSyntaxTree, "invalid use of ...")
go/types/resolver.go:420:							check.softErrorf(tparam0, code, "func %s must have no type parameters", name)
go/types/resolver.go:424:							check.softErrorf(d.decl.Name, code, "func %s must have no arguments and no return values", name)
go/types/resolver.go:434:							check.softErrorf(obj, MissingInitBody, "func init must have a body")
go/types/resolver.go:730:		check.softErrorf(obj, UnusedImport, "%q imported and not used", path)
go/types/resolver.go:732:		check.softErrorf(obj, UnusedImport, "%q imported as %s and not used", path, obj.name)
go/types/stmt.go:72:		check.softErrorf(v, UnusedVar, "declared and not used: %s", v.name)
go/types/stmt.go:707:				check.softErrorf(lhs, NoNewVar, "no new variable on left side of :=")
go/types/stmt.go:782:				check.softErrorf(lhs, UnusedVar, "%s declared and not used", lhs.Name)
go/types/stmt.go:848:			check.softErrorf(s, InvalidPostDecl, "cannot declare in post statement")
go/types/typexpr.go:168:					check.softErrorf(e, MisplacedConstraintIface, "cannot use type %s outside a type constraint: interface is (or embeds) comparable", typ)
go/types/typexpr.go:170:					check.softErrorf(e, MisplacedConstraintIface, "cannot use type %s outside a type constraint: interface contains type constraints", typ)
go/types/typexpr.go:449:				check.softErrorf(atPos(pos), InvalidTypeArg, "%v", err)
go/types/union.go:131:				check.softErrorf(tlist[i], InvalidUnion, "overlapping terms %s and %s", t, terms[j])
////

以下で、ソフトなエラーとそうでない重篤なエラーの例を確認できます。

goexample::typecheckerrors[]

goexample::typecheckerrors[output]

== パッケージの型情報

`types.Config.Check()` によって得られる型情報は、パッケージに対応する `types.Package` と、補助的で詳細な情報である `types.Info` で表現されます。

=== types.Package

godoc::go/types.Package[]

`types.Package` 構造体は公開されたフィールドを持たないため、メソッドからアクセスします。

あまり意味のない例ですが、以下では `$GOROOT/src/cmd/cover` ディレクトリのソースコードの型チェックを行っています。

goexample::typechecknameandpath[]

goexample::typechecknameandpath[output]

== スコープ

`types.Package` 構造体において `Path` や `Name` などの基本的な情報の他に有用なのは、解析されたパッケージのスコープ情報でしょう。

Goのソースコードに登場する名前はレキシカルスコープを持ち、その有効範囲は静的に決まります。型チェックの過程では、このスコープにしたがって、ソースコード中の識別子がどの宣言に由来するものであるかを解決します。

=== スコープを形成するブロック

Goのスコープはブロックにもとづいて作られます。ブレース（`{ ... }`）による明示的なブロックのほかにも、暗黙に作られるブロックがあります。link:https://go.dev/ref/spec#Blocks[Blocks]およびlink:https://go.dev/ref/spec#Declarations_and_scope[Declarations and scope - The Go Programming Language Specification]に述べられていますが、重要な部分を抄訳します：

* 暗黙のユニバースブロック（universe block）は、すべてのソースコードを含みます。あらかじめ宣言された名前（`int` や `nil`、`len` など）はここに属します。
* パッケージは暗黙のパッケージブロック（package block）を持ち、パッケージを構成するすべてのソースコードを含みます。トップレベルに宣言された定数、型、変数、関数（メソッドを除く）の名前はここに属します。
* ファイルは暗黙のファイルブロック（file block）を持ち、ひとつのファイルのソースコードを含みます。インポートされたパッケージの名前はここに属します。
* `if`、`for`、`switch` 文はそれ自身が暗黙のブロックを作ります。`switch` や `select` の各節（case）も同様です。

=== types.Scope

`types` パッケージでは、スコープを `types.Scope` 構造体で表現します。パッケージ全体のスコープ（パッケージブロックに対応するもの）は `types.Package` の `Scope()` メソッドで得られます。

godoc::go/types.Package.Scope[]

godoc::go/types.Scope[]

`Scope` 構造体のメンバーは公開されておらず、メソッドでその内容に問い合わせる必要があります。

スコープは大雑把にいうと、名前からそれが表すシンボル（<<オブジェクト>>、後述）へのマッピングです。`Names()` でスコープ内の名前の一覧を、`Lookup()` で名前に対応するオブジェクトを得られます。

godoc::go/types.Scope.Names[]

godoc::go/types.Scope.Lookup[]

また、スコープ同士は入れ子による木構造をつくります。`Parent()` および `Children()` メソッドにより、その親（ひとつ外側のスコープ）や子にアクセスできます。

godoc::go/types.Scope.Parent[]

godoc::go/types.Scope.Children[]

以下の例では、パッケージのスコープから子スコープを再帰的にたどり、スコープ内のオブジェクトを印字します。

goexample::typesscopetree[]

goexample::typesscopetree[output]

// ちなみにデバッグ情報を Scope.String() からしか取り出せないのは `gofind 'go/types.Scope.comment' go/types` で確認できる。

パッケージのスコープの下にファイルのスコープがあり、さらにその下に関数や `for` 文によるスコープが連なっています。

// TODO: token.Pos を使うメソッドも紹介する

=== ユニバーススコープ

最も外側にあるユニバースブロックのスコープは、`types.Universe` として定義されています。

以下の例では、ユニバーススコープに定義されている名前を列挙しています。

goexample::typesuniverse[]

goexample::typesuniverse[output]

組み込みの関数や型がユニバーススコープに属していることが分かります。

== オブジェクト

`go/types` では、名前解決によって識別子（`ast.Ident`）と対応づけられたシンボルまたはterm:名前をつけられた言語上の要素[named language entity]をterm:オブジェクト[object]と呼んでいます。このオブジェクトは名前や型、その実体の情報を持ちます。<<スコープ>>が名前から引くのはこのオブジェクトです。

オブジェクトは `types.Object` インタフェースとして表現されています。

godoc::go/types.Object[]

`Name()` や `Pos()` でオブジェクトの名前や宣言された位置を、`Type()` でその型を、`Parent()` でそのオブジェクトが宣言されたスコープを得られます。

オブジェクトの種類は `types.Object` を実装する具体的なデータ型によって区別されます。`types` パッケージで表現されるオブジェクトの種類と、対応するデータ型は以下のようになっています。

* 組み込み関数（`*types.Builtin`）
* 定数（`*types.Const`）
* 関数（`*types.Func`）
* ラベル（`*types.Label`）
* `nil` （`*types.Nil`）
* インポートされたパッケージ（`*types.PkgName`）
* 宣言された型（`*types.TypeName`）
* 宣言された変数など（`*types.Var`）
// ^ などってのは struct field も含むから

これらについて、以下で見ていきます。

=== types.Builtin

組み込み関数を表します。組み込み関数は決まった型を持たないため、`Type()` はinvalidな型を返します。

goexample::typesbuiltin[]

goexample::typesbuiltin[output]

=== types.Const

定数を表します。`Val()` メソッドは、その定数値を表す `go/constant` パッケージの値を返します。

godoc::go/types.Const.Val[]

https://go.dev/ref/spec#Constant_expressions[定数式]は型チェック時に評価され、値としてオブジェクトに保持されます（TODO: 定数畳み込み）。

goexample::typesconst[]

goexample::typesconst[output]

=== types.Func

関数を表します。より詳細には、

- 宣言された関数
- 具象メソッド
- （インタフェースの）抽象メソッド

です。

以下で、それぞれの場合（トップレベルの関数 `F`、型 `*T` のメソッド `F`、インタフェース `I` のメソッド `F`）の出現を確認しています。

goexample::typesfunc[]

goexample::typesfunc[output]

<1> パッケージスコープ内の名前にアクセスします。`F` はトップレベルの関数に、`T` および `I` は型名に対応するオブジェクトとして取得します。
<2> 型 `T` に属する最初のメソッドとして、`T.F()` に対応するオブジェクトを取得します。
<3> 型 `I` が指すインタフェース `interface { F() }` の最初の（抽象）メソッドとして、`I.F()` に対応するオブジェクトを取得します。

インタフェースの抽象メソッドと、それ以外の具象メソッドに対応するオブジェクトへアクセスする方法は微妙に異なりますが、これはあとの節で詳しく触れます。

=== types.PkgName

`import` 宣言によってインポートされたパッケージの名前を表します。

`Imported()` メソッドで、インポートされたパッケージに関する情報を保持する <<types.Package,`types.Package` 構造体>>を得られます。これは `Config.Check` で得られるのと同様のものです。

以下の例では、`fmtPkg` という名前でインポートした `fmt` パッケージと、同パッケージのエクスポートする `Errorf` 関数に対応するオブジェクトを取得しています。

インポートしたパッケージの名前はパッケージスコープではなくファイルスコープに導入されるため、後の節で説明する<<types.Info,`Info` 構造体>>を使ってファイルスコープを取得しています。

goexample::typespkgname[]

goexample::typespkgname[output]

NOTE: ファイル先頭の `package` 節で指定された名前はスコープに導入されないので、自パッケージの名前が `PkgName` の形で登場することはありません。

=== types.TypeName

名前をつけられた型を表します。具体的には、以下のいずれかに対応します。

* 定義された型（`types.Named`）… `type T struct{}` など
* 型エイリアス（`types.Alias`）… `type A = T` など
* 型パラメータ（`types.TypeParam`）… `func F[P any]()` の `P`
* あらかじめ宣言された型 … `int` や `error` など

`TypeName` が表す型は、`Type()` メソッドで得られる `types.Type` になります。以下のサンプルコードで、「あらかじめ宣言された型」がそれぞれどのように表現されているか確認します。

goexample::typesuniversetypename[]
goexample::typesuniversetypename[output]

ここから、いくつかのことが見てとれます。

* `any` は `interface{}` のエイリアスです。
* `comparable` は `interface{ comparable }` に名前をつけたもの、という扱いです。循環参照みたいですが、参照先は「内部的にcomparableフラグが立っている」ようなインタフェースとして表現されています。
// ^ defPredeclaredTypes
* `error` は `interface{ Error() string }` に名前をつけたものです。
* `byte` と `rune` はエイリアスだとみなされますが、その表現は `types.Basic` です。実際、それぞれ `uint8` と `int32` と同じ属性を持ち、別の名前を持つ型として表現されています。
// ^ basicAliases

// 型エイリアスは since 1.22

=== types.Var

宣言された変数を表します。ここでいう変数には、`var` や `:=` によって定義された変数のほか、以下も含まれます。

* 関数のパラメータ・戻り値
* メソッドのレシーバ
* 構造体のフィールド

これらのうちどれであるかは、`Kind()` メソッドが返す `types.VarKind` で区別できます。

godoc::go/types.PackageVar[]

==== フィールドを表すオブジェクト

構造体のフィールドを表す `Var` については、以下のメソッドでフィールドとしての情報を得られます。

`IsField()` は、その `Var` が構造体のフィールドであるかどうかを返します。`Kind()` を `types.FieldVar` と比較することへのショートカットです。

godoc::go/types.Var.IsField[]

`Embedded()` は、その `Var` が埋め込みフィールドであるかどうかを返します。同じ挙動の `Anonymous()` もありますが、後方互換性のためだけに残されているので、新しく書くコードでは `Embedded()` を使いましょう。

godoc::go/types.Var.Embedded[]

以下の例では、構造体 `S` のフィールドについて、その名前と型、`Embedded()` の結果を印字しています。

goexample::typesvarembedded[]
goexample::typesvarembedded[output]

==== 型パラメータのインスタンス化によって生成されるオブジェクト

ジェネリックな型や関数をインスタンス化すると、型パラメータに依存するフィールドや引数を表す `Var` は、具体化された新しいオブジェクトとして生成されます。

このようにして合成された `Var` は対応するソースコード上の定義が存在しませんが、`Origin()` メソッドを使うことで、そのもとになった `Var` を得られます。

godoc::go/types.Var.Origin[]

以下で、インスタンス化されたジェネリックな型 `Gen[string]` のフィールドやメソッドの引数がどのように `Var` として表現されるかを確認します。

goexample::typesvarorigin[]

goexample::typesvarorigin[output]

// TODO: Func.Origin() も同様。型パラメータの節を書くときに合わせて触れる

== types.Info

さて、`types.Scope` のメソッドを使うことで、パッケージ中に登場した名前に関する情報をオブジェクトとして得ることは一応可能です。しかしこれだけでは、

* あるオブジェクトがどこで定義されたのか
* ある式にどんな型が与えられたのか

などについて（ただちには）知ることができません。そこで `Check` 関数の最後の引数に渡す構造体、`types.Info` の出番となります。

godoc::go/types.Info[]

`types.Info` は型チェック中に得られた、詳細な情報を保持する構造体です。

WARNING: WIP

== 型の情報

=== types.Type

[appendix]
== types.Objectの階層

----
include::listings/types-object-hierarchy.txt[]
----

[appendix]
== types.Typeの階層

----
include::listings/types-type-hierarchy.txt[]
----
