= ファイルの構文解析

ここまで式の構文解析を例にとって見てきましたが、実践においては、Goのソースコードはファイルやパッケージの単位で扱うことが普通です。ここからはファイル全体を構文解析する方法を見ていきます。

== ファイルの構造

まず、Goのソースコードファイルの構造を確認しておきましょう。

https://go.dev/ref/spec#Source_file_organization[The Go Programming Language Specification - Source file organization] によれば、ひとつのファイルの中には

1. パッケージ名
2. `import` 節
3. 値や関数などトップレベルの宣言

が、この順番で現れることになっています。

== parser.ParseFile

Goのソースコードファイルの構文解析を行うには `parser.ParseFile` を使用します。

godoc::go/parser.ParseFile[]

第二引数の `filename` と第三引数の `src` はふたつで一組になっていて、構文解析するソースコードを指定します。`src == nil` であるときは `filename` に指定されたファイルの内容をソースコードとして読み込みます。それ以外の場合は `src` をソースコードとして読み込み、`filename` はソースコードの位置情報にだけ使われます。`src` は `interface{}` ですが、指定できるのは `string`、`[]byte`、`io.Reader` のいずれかのみです。

第一引数の `fset` は構文解析によって得られた構文木のノードの詳細な位置情報を保持する `token.FileSet` 構造体へのポインタです。詳しくは<<ソースコード中の位置>>で説明しますが、基本的に `token.NewFileSet()` で得られるものを渡せば十分です。

最後の引数 `mode` では構文解析する範囲の指定などが行えます。後で<<コメントとドキュメント>>を扱うときに少し触れます。

goexample::parsefile[]
goexample::parsefile[output]

例では `src` 変数のもつソースコードを構文解析し、トップレベルの宣言を印字します。今回は `import` 宣言が `*ast.GenDecl` として、関数 `func f` が `*ast.FuncDecl` として得られました。

== ast.File

ソースファイルは `ast.File` 構造体で表現され、パッケージ名やトップレベルの宣言の情報を含んでいます。

godoc::go/ast.File[]

他にもいろいろなフィールドがありますが、

* `Package` は<<ソースコード中の位置>>、
* `Scope` と `Unresolved` は<<スコープ>>、
* `Doc` と `Comments` は<<コメントとドキュメント>>

で解説します。

// Imports は Decls のうち IMPORT なものをフラットに並べてるだけで parser.ImportsOnly なときに便利ってくらい？
// 5be77a204bee72c81a8f0182d0a23bfd32b36ab9

== 構文木の探索

<<構文ノードのインタフェース>>で述べたように、構文木のノードは `ast` パッケージのインタフェースとして得られます。そのため、具体的な内容を知るにはtype assertionやtype switchを用いなければなりません。これを手で丁寧に書いていくのは大変で間違いも起きがちですが、`ast.Inspect` 関数で構文ノードに対する（深さ優先）探索を行えます。

godoc::go/ast.Inspect[]

`node` から始まり、子ノードを再帰的に探索しつつにコールバック関数 `f` が呼ばれます。子ノードの探索を終えるごとに、引数 `nil` でコールバックが呼ばれます。コールバック関数では `false` を返すことで、そのノードの子供以下への探索を打ち切ることができます。

以下は先ほどのソースコードファイル中の識別子を一覧する例です。訪問したノードの具体的な型を知るために、type assertionをおこなっています。

goexample::listidents[]
goexample::listidents[output]

パッケージ名（`p`）や変数名（`n`）などの識別子が構文木に含まれていることが確認できます。

NOTE: もうひとつの方法として、`ast.Visitor` インタフェースを実装して `ast.Walk(v ast.Visitor, node ast.Node)` を使うこともできます。実際 `ast.Inspect` の内部では `ast.Walk` が使われています。
