= ファイルの構文解析

ここまで式の構文解析を例にとって見てきましたが、実践においては、Goのソースコードはファイルやパッケージの単位で扱うことが普通です。ここからはファイル全体を構文解析する方法を見ていきます。

== ファイルの構造

まず、Goのソースコードファイルの構造を確認しておきましょう。

https://go.dev/ref/spec#Source_file_organization[The Go Programming Language Specification - Source file organization]によれば、ひとつのファイルの中には

1. パッケージ名
2. `import` 節
3. 値や関数などトップレベルの宣言

が、この順番で現れることになっています。

== parser.ParseFile

Goのソースコードファイルの構文解析を行うには `parser.ParseFile` を使用します。

godoc::go/parser.ParseFile[]

第二引数の `filename` と第三引数の `src` はふたつで一組になっていて、構文解析するソースコードを指定します。`src == nil` であるときは `filename` に指定されたファイルの内容をソースコードとして読み込みます。それ以外の場合は `src` をソースコードとして読み込み、`filename` はソースコードの位置情報にだけ使われます。`src` は `interface{}` ですが、指定できるのは `string`、`[]byte`、`io.Reader` のいずれかのみです。

第一引数の `fset` は構文解析によって得られた構文木のノードの詳細な位置情報を保持する `token.FileSet` 構造体へのポインタです。詳しくは<<ソースコード中の位置>>で説明しますが、基本的に `token.NewFileSet()` で得られるものを渡せば十分です。

最後の引数 `mode` では構文解析する範囲の指定などが行えます。これについては次の<<parser.Mode>>で説明します。

goexample::parsefile[]
goexample::parsefile[output]

例では `src` 変数のもつソースコードを構文解析し、トップレベルの宣言を印字します。今回は `import` 宣言が `*ast.GenDecl` として、関数 `func f` が `*ast.FuncDecl` として得られました。

== parser.Mode

`parser.ParseFile` の最後の引数 `mode` は `parser.Mode` 型の値で、構文解析の挙動をカスタマイズすることができます。

godoc::go/parser.Mode[]
godoc::go/parser.PackageClauseOnly[]

複数のフラグを指定する場合は `parser.ParseComments|parser.SkipObjectResolution` のようにビット和をとります。

主なフラグは以下の通りです。

`PackageClauseOnly`、`ImportsOnly`:: それぞれパッケージ節、`import` 宣言までを解析したところで構文解析を打ち切ります。
`ParseComments`:: ソースコード中のコメントも結果に含めます。指定しない場合、コメントは読み捨てられます。<<コメントとドキュメント>>を取り扱うのに必要です。
`SkipObjectResolution`:: 構文解析の段階で行われる識別子の解決をスキップします。この機能が生成する `ast.Object` などはすでに非推奨となっており、`ParseFile` のドキュメントでもこのフラグの指定が推奨されています。詳しくは<<ast-object-deprecation>>で解説します。

NOTE: `DeclarationErrors` は宣言に関するエラーを報告するフラグとなっていますが、内部では非推奨となった機構を利用しているため（<<ast-object-deprecation>>）、使用しないほうがいいかもしれません。

== ast.File

ソースファイルは `ast.File` 構造体で表現され、パッケージ名やトップレベルの宣言の情報を含んでいます。

godoc::go/ast.File[]

他にもいろいろなフィールドがありますが、

* `Package` は<<ソースコード中の位置>>、
* `Doc` と `Comments` は<<コメントとドキュメント>>

// TODO: GoVersion について触れる

で解説します。

`Scope` と `Unresolved` はGo 1.22で非推奨となりました。詳しくは<<ast-object-deprecation>>で解説します。

// Imports は Decls のうち IMPORT なものをフラットに並べてるだけで parser.ImportsOnly なときに便利ってくらい？
// 5be77a204bee72c81a8f0182d0a23bfd32b36ab9

== 構文木の探索

<<構文ノードのインタフェース>>で述べたように、構文木のノードは `ast` パッケージのインタフェースとして得られます。構文木を辿っていくにはtype switchなどを用いて具体的な型を判別し、それぞれに応じた処理を行う必要がありますが、このような処理をサポートする関数が `ast` パッケージには用意されています。

=== ast.Preorder

`ast.Preorder` 関数をfor rangeループとともに用いることで、構文木のノードを行きがけ順（preorder）深さ優先で辿れます。

godoc::go/ast.Preorder[]

NOTE: 深さ優先探索において、行きがけ順（preorder）では、親ノードを先に訪問し、その後に子ノードを訪問します。

以下は先ほどのソースコードファイル中の識別子を一覧する例です。訪問したノードの具体的な型を知るために、type assertionをおこなっています。

goexample::listidents[]
goexample::listidents[output]

パッケージ名（`p`）や変数名（`n`）などの識別子が構文木に含まれていることが確認できます。

=== ast.PreorderStack

単純にすべてのノードを個別に走査するのではなく、根からそのノードに至るまでのスタックを参照したり、部分木をスキップしたりと、より柔軟な探索をしたい場合には `ast.PreorderStack` が使えます。

godoc::go/ast.PreorderStack[]

`Preorder` と名前は似ていますが形は異なっており、コールバックを用います。

コールバック `f` の第二引数 `stack` には、根 `root` からそのノードに至るまでのノードが順に並んでいます。ノード `n` 自身は含まれません。また `f` が `false` を返した場合、そのノードの子孫はスキップされます。

先ほどの識別子を一覧する例を、それぞれの識別子が根からどのようなノードを経て現れるのかも表示するように書き換えてみましょう。

goexample::preorderstack[]
goexample::preorderstack[output]

NOTE: より低レベルな方法として `ast.Inspect`、`ast.Walk` を使うこともできますが、ここでは紹介しません。とくに `ast.PreorderStack` は `ast.Inspect` でよくある間違いを回避する目的で導入されました（link:https://github.com/golang/go/issues/73319[golang/go#73319]）。
