[#ast-object-deprecation]
= `ast.Object` の非推奨化

`ast.Object` やそれらにまつわるAPIは1.22で非推奨化されました（<https://go.dev/doc/go1.22#minor_library_changes>）。以下では、これらのもともとの動機と、非推奨化の経緯について概説します。

== `ast.Object`

ソースコード中の識別子を表す `ast.Ident` には、`*ast.Object` 型の `Obj` というフィールドが定義されていました。

godoc::go/ast.Ident[]

`go/ast` や `go/types` では、term:名前をつけられた言語上の要素[named language entity]をterm:オブジェクト[object]と呼んでおり、構文上のオブジェクトはこの `ast.Object` によって表されています。

たとえば以下のコードにおける `x` のように、同じ名前を持つ識別子でもその指す実体が異なっていることがありますが、それを構文解析の段階で区別しようというものです。

[source,go]
----
package p

import x "pkg"

func f() {
    if x := x.f(); x != nil {
        x(func(x int) int { return x + 1 })
    }
}
----

== 構文解析だけでは不十分な例

ただし、構文解析だけでは全ての名前を正しく解決できるわけではありません。

有名な例として、以下のプログラムには `T{k: 0}` という同じ形をしたコードが出現します。ここで `k` が指すものは一方ではトップレベルの定数、もう一方では構造体のフィールドと、それぞれ違ったものになります（link:https://github.com/golang/example/tree/master/gotypes[`go/types`: The Go Type Checker] より）。

goexample::indeterminableident[]

また、名前なしの `import` 文によって導入されたパッケージ名は構文解析だけでは判定できません。

[source,go]
----
import "github.com/motemen/go-loghttp" // loghttp という名前が導入される
----

これらも含めて正しく（Go言語の仕様通りに）名前のスコープを決定するには、<<型解析>>の手続きを経なくてはなりません。

== 非推奨化の経緯

上記の問題と、それに起因する利用者の混乱を理由に、link:https://github.com/golang/go/issues/52463[golang/go#52463]で `ast.Object` の非推奨化が決定されました。

Go 1.22で `ast.Object` をはじめとして `ast.Ident.Obj`、`ast.Scope`、`ast.File.Scope`、`ast.File.Unresolved`, `ast.Importer`、`ast.Package`、`ast.NewPackage` が非推奨化されました。

またその後のGo 1.25では、`ast.FilterPackage`、`ast.PackageExports`、`ast.MergePackageFiles`、`ast.MergeMode` が非推奨化されています。これらのAPIも、`ast.Object` 関連の機構にのみ依存していたためです（<https://go.dev/doc/go1.25#minor_library_changes>）。
