= 構文ノードの実装

== ast.Node

抽象構文木のノードに対応する構造体は、すべて `ast.Node` インタフェースを実装しています。

godoc::go/ast.Node[]

定義を見れば分かるとおり、`ast.Node` インタフェース自身はその<<ソースコード中の位置>>を提供するだけであり、このままでは構文木に関する情報を得ることはできません。構文木を探索・操作するにはtype assertionやtype switchによる具体的な型への変換が必要になります。

構文木のノードを大別するため、`ast.Node` を実装するサブインタフェースが定義されています：

`ast.Decl`:: 宣言（declaration）。`import` や `type` など
`ast.Stmt`:: 文（statement）。`if` や `switch` など
`ast.Expr`:: 式（expression）。識別子や演算、型など

ファイルやコメントなど、これらに分類されない構文ノードも存在します。

以下でこれらサブインタフェースと、その実装のうち主要なものを見ていきます。

NOTE: <<ast.Nodeの階層>>で `ast.Node` を実装する型の完全な一覧を確認できます。

== ast.Decl

`ast.Decl` インタフェースはGoソースコードにおける宣言（declaration）に対応する構文木のノードを表します。Goの宣言は

* パッケージのインポート（`import`）
* 変数および定数（`var`、`const`）
* 型（`type`）
* 関数およびメソッド（`func`）

と4種類に分けられますが、`ast.Decl` インタフェースを実装している構造体は `*ast.FuncDecl` と `*ast.GenDecl` の2つのみです。前者は名前どおり関数及びメソッドの宣言に相当し、後者が残りすべてをカバーします。

=== ast.FuncDecl

godoc::go/ast.FuncDecl[]

`ast.FuncDecl` 構造体は関数の宣言に対応します。`Recv` フィールドはそのレシーバを表しており、これが `nil` である場合は関数を、そうでない場合はメソッドの宣言を表します。

`Recv` の型である <<ast.FieldList,`*ast.FieldList`>>は識別子と型の組のリストで、関数のパラメータや構造体のフィールドを表すのに使われます。

NOTE: `FieldList` はその名の通り複数の組を表しますが、Goの文法上、レシーバとしてはただ1つの組のみが有効です。が構造体のフィールド宣言の表現などにも使われる `FieldList` が再利用されている形です。

[WARNING]
====
上記の事情にも関わらず、`go/parser` は複数の組からなるレシーバをエラーなく解析します！ コメントによると、シンプルさとロバスト性のためだということです。

TODO: なんかいい感じに引用スタイル

.src/go/parser/parser.go
----
The parser accepts a larger language than is syntactically permitted by
the Go spec, for simplicity, and for improved robustness in the presence
of syntax errors. For instance, in method declarations, the receiver is
treated like an ordinary parameter list and thus may contain multiple
entries where the spec permits exactly one. Consequently, the corresponding
field in the AST (ast.FuncDecl.Recv) field is not restricted to one entry.
----
====

=== ast.GenDecl

関数以外の宣言、`import`、`const`、`var`、`type` は `ast.GenDecl` がまとめて引き受けます。

godoc::go/ast.GenDecl[]

`Specs` フィールドはスライスであり、その要素がそれぞれ `ast.Spec` インタフェースであると定義されています。実際には、要素の具体的な型は `Tok` フィールドの値によってひとつに決まります。

|===
|`Tok` の値|`Specs` の要素の型|表す構文

|`token.IMPORT`|`*ast.ImportSpec`|`import` 宣言
|`token.CONST`|`*ast.ValueSpec`|`const` 宣言
|`token.TYPE`|`*ast.TypeSpec`|`type` 宣言
|`token.VAR`|`*ast.ValueSpec`|`var` 宣言
|===

これらの宣言には、以下のようにグループ化できるという共通点があります。グループ化された宣言のひとつが `Specs` スライスのひとつの要素に対応します。

[source,go]
----
import (
    "foo"
    "bar"
)

const (
    a = 1
    b = 2
)

var (
    x int
    y bool
)

type (
    s struct{}
    t interface{}
)
----

== ast.Stmt

`ast.Stmt` インタフェースはGoソースコードにおける https://golang.org/ref/spec#Statements[文] に対応する構文木のノードを表します。文はプログラムの実行を制御するもので、`go/ast` パッケージの実装では以下のように分類されています：

// ast.go 内の順番

.ast.Stmtの分類
* 宣言（`ast.DeclStmt`）
* 空の文（`ast.EmptyStmt`）
* ラベル付き文（`ast.LabeledStmt`）
* 式だけの文（`ast.ExprStmt`）
* チャンネルへの送信（`ast.SendStmt`）
* インクリメント・デクリメント（`ast.IncDecStmt`）
* 代入または定義（`ast.AssignStmt`）
* `go` （`ast.GoStmt`）
* `defer`（`ast.DeferStmt`）
* `return`（`ast.ReturnStmt`）
* `break`、`continue`、`goto`、`fallthrough`（`ast.BranchStmt`）
* ブロック（`ast.BlockStmt`）
* `if`（`ast.IfStmt`）
* 式による `switch`（`ast.SwitchStmt`）
* 型による `switch`（`ast.TypeSwitchStmt`）
* `switch` 中のひとつの節（`ast.CaseClause`）
* `select`（`ast.SelectStmt`）
* `select` 中のひとつの節（`ast.CommClause`）
* `range` を含まない `for`（`ast.ForStmt`）
* `range` を含む `for`（`ast.RangeStmt`）

=== ast.SwitchStmt

[WARNING]
====
TODO

https://golang.org/ref/spec#ExprSwitchStmt

* `Init` は `switch *x := 1*; t {`
* `Tag` は `switch x := 1; *t* {`
====

=== ast.TypeSwitchStmt

[WARNING]
====
TODO

https://golang.org/ref/spec#TypeSwitchStmt

* `Init`
* `Assign`

====

== ast.Expr

`ast.Expr` インタフェースはおもにGoソースコードにおける https://golang.org/ref/spec#Expressions[式] および https://golang.org/ref/spec#Types[型] に対応する構文木のノードを表します。`go/ast` パッケージの実装では以下のように分類されています：

NOTE: `ast.Ellipsis` や `ast.KeyValueExpr` のように、それ単体では式となり得ないノードも `ast.Expr` を実装していますが、このおかげでこれらを含むノードの実装が簡単になっているようです。

* 識別子（`ast.Ident`）
* `...`（`ast.Ellipsis`）
* 基本的な型のリテラル（`ast.BasicLit`）
* 関数リテラル（`ast.FuncLit`）
* https://golang.org/ref/spec#Composite_literals[複合リテラル]（`ast.CompositeLit`）
* 括弧（`ast.ParenExpr`）
* セレクタまたは修飾された識別子（`x.y`）（`ast.SelectorExpr`）
* 添字アクセス（`ast.IndexExpr`）
* スライス式（`ast.SliceExpr`）
* 型アサーション（`ast.TypeAssertExpr`）
* 関数またはメソッド呼び出し（`ast.CallExpr`）
* ポインタの間接参照またはポインタ型（`*p`）（`ast.StarExpr`）
* 単項演算（`ast.UnaryExpr`）
* 二項演算（`ast.BinaryExpr`）
* 複合リテラル中のキーと値のペア（`key: value`）（`ast.KeyValueExpr`）
* 配列またはスライス型（`ast.ArrayType`）
* 構造体型（`ast.StructType`）
* 関数型（`ast.FuncType`）
* インタフェース型（`ast.InterfaceType`）
* マップ型（`ast.MapType`）
* チャンネル型（`ast.ChanType`）

=== ast.Ident

godoc::go/ast.Ident[]

`ast.Ident` はコード中の識別子を表し、変数名をはじめパッケージ名、ラベルなどさまざまな場所に登場します。

`Obj` フィールドはその実体を表す `ast.Object` への参照になっています。詳しくは <<スコープとオブジェクト>>で触れます。

=== ast.StructTypeとast.InterfaceType

godoc::go/ast.StructType[]

godoc::go/ast.InterfaceType[]

これら2つの構造体はそれぞれ構造体、インタフェースを表現します。また、`Incomplete` フィールドを持っています。これらは通常 `false` ですが、<<ast.Filter,フィルタ>>によってノード中のフィールドやメソッドの宣言が取り除かれる際に `true` となり、ソースコードとノードに乖離があることを示します。`go doc` が出力する "`// Has unexported fields.`" はこの値を参照しています。

goexample::structtypeincomplete[]
goexample::structtypeincomplete[output]

== その他のノード

以上の3種類に分類されないノードもいくつか存在します。

=== ast.Commentとast.CommentGroup

godoc::go/ast.Comment[]

godoc::go/ast.CommentGroup[]

`ast.Comment` はひとつのコメント（`// ...` または `/* ... */`）に、`ast.CommentGroup` は連続するコメントに対応します。<<コメントとドキュメント>>で詳しく見ます。

=== ast.Fieldとast.FieldList

godoc::go/ast.Field[]

godoc::go/ast.FieldList[]

それぞれ、識別子と型の組ひとつ、そのリストに対応します。

`ast.FieldList` は以下の構造体に含まれています：

* `ast.StructType`    ...... 構造体のフィールドのリストとして
* `ast.InterfaceType` ...... インタフェースのメソッドのリストとして
* `ast.FuncType`      ...... 関数のパラメータおよび返り値として
* `ast.FuncDecl`      ...... メソッドのレシーバとして

`ast.Field` の `Tag` は構造体のフィールドである場合のみ存在しえます。

WARNING: TODO Names のふるまい方; nil と複数

// git grep -w Tag src/go/parser; parseStructType -> parseFieldDecl

[appendix]
== ast.Nodeの階層

----
include::../listings/ast-node-hierarchy.txt[]
----

// TODO: ast.Filter
// TODO: ast.Fprint
