= go doc

"go doc" はパッケージのAPIのドキュメントを閲覧する機能を提供するサブコマンドです。
`go doc go/ast Node` のようにパッケージやシンボルを指定すると、そのドキュメントを表示します。

....
% go doc go/ast Node
type Node interface {
        Pos() token.Pos // position of first character belonging to the node
        End() token.Pos // position of first character immediately after the node
}
    All node types implement the Node interface.
....

パッケージ名は完全なパスでなくてもよく、その場合はGOPATH以下からマッチするものを探してきます。

....
% go doc template
package template // import "html/template"

Package template (html/template) implements data-driven templates for
...

% go doc ast.Node
package ast // import "go/ast"

type Node interface {
        Pos() token.Pos // position of first character belonging to the node
        End() token.Pos // position of first character immediately after the node
}
    All node types implement the Node interface.
....

ソースは `src/cmd/doc/` 以下にあります。

// TODO: godoc との関係
// TODO: 概要

`go doc` が行う処理は以下のように分解できます。

* コマンドライン引数の解決
* ソースコードの解析
* ドキュメントの表示

これから、それぞれの処理について詳しく見ていきます。

== 引数の解決（`parseArgs`）

`go doc` サブコマンドに与えられるコマンドライン引数は、ユーザの意図を表した以下のような形の文字列のリストになっています。

.go doc -h
----
% go doc -h
Usage of [go] doc:
        go doc
        go doc <pkg>
        go doc <sym>[.<method>]
        go doc [<pkg>].<sym>[.<method>]
        go doc <pkg> <sym>[.<method>]
----

さまざまな形式がありますが、大きく

最初に、引数で指定された要件にしたがってドキュメントの元となるソースコードを取得します。

`go doc` への引数の与え方はさまざまで、パッケージを指定する方法には次の3パターンがあります：

a. カレントディレクトリのソースコードを対象にする（例：`go doc`）。
b. 完全なパスで指定されたパッケージを対象にする（例：`go doc encoding/json`）。
c. 指定されたパスの一部からパッケージを探しだす（例：`go doc json`）。

これに加えて、パッケージ内のシンボルおよびそのメソッドも指定されることがあります。

カレントディレクトリを対象にする場合およびパッケージが指定されている場合（aおよびb）は、`go/build` のAPI `build.Import` を使って簡単にソースコードの所在を示す `build.Package` が得られます。

そうでない場合（c）、パスの一部が一致するパッケージを発見する必要があります。ここでも `go/build` のAPIを利用し、`build.Default.GOROOT` と `build.Default.GOPATH` 以下のディレクトリを探索します。`go doc` コマンドが実行された時点でこの探索のためのgoroutineが起動していて、すばやく結果を返せるようになっています。

== ソースコードの解析（`parsePackage`）

ドキュメント情報を得るためには、ソースコードを解析する必要があります。パッケージの情報が手元にあるので `parser.ParseDir` でディレクトリ内のファイルを一度に解析できますが、その際第3引数の `filter` を指定して `GoFiles` や `CgoFiles` に含まれないものを除去します。こうすることで、実行環境（`GOOS` や `GOARCH`）に合わせたソースコードのみを解析対象としています。

[source,go]
----
pkgs, err := parser.ParseDir(fs, pkg.Dir, include, parser.ParseComments)
----

その後 `doc.New` して得られた `doc.Package` から `Package` 構造体を生成します。

== ドキュメントの表示（`Package.packageDoc` など）

`Package` 構造体の以下のメソッドがモードに応じて選ばれ、ユーザに表示される内容を生成します。

* `packageDoc` ... パッケージのドキュメントを表示
* `symbolDoc`  ... シンボル（型、関数、メソッドなど）のドキュメントを表示
* `methodDoc`  ... ある型のメソッドのドキュメントを表示

ドキュメントを表示するなかで対象のソースコードにおける定義が必要になった場合（`go doc go/ast File` など）、`format.Node` で生成されます。`ast.FuncDecl` を表示する際は `Body` フィールドに `nil` を代入することで、宣言のみが表示されるようにしています。


